rpnew_prog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from filebrowser.sites import site
from users import views as user_views
from pagine.views import HomeTemplateView
from direzione.views import (PrivacyTemplateView, MembershipTemplateView,
    AboutTemplateView, InstructionsTemplateView, )#
from . import views

admin.site.site_header = 'Amministrazione RP'
admin.site.site_title = 'Amministrazione RP'

urlpatterns = [
    path('admin/filebrowser/', site.urls),
    path('admin/', admin.site.urls),
    path('registration/', user_views.RegistrationFormView.as_view(),
        name='registration'),
    path('contacts/', user_views.ContactFormView.as_view(), name='contacts'),
    path('accounts/', include('users.urls')),
    path('search/', views.search_results, name='search_results'),
    path('', HomeTemplateView.as_view()),
    path('privacy/', PrivacyTemplateView.as_view(), name='privacy'),
    path('iscrizioni/', MembershipTemplateView.as_view(), name='membership'),
    path('istruzioni/', InstructionsTemplateView.as_view(), name='instructions'),
    path('storia/', AboutTemplateView.as_view(), name='about'),
    path('convenzioni/', include('direzione.urls.conventions',
        namespace = 'conventions')),
    path('calendario/', include('pagine.urls.events', namespace = 'pagine')),
    path('articoli/', include('pagine.urls.posts', namespace = 'blog')),
    path('luoghi/', include('pagine.urls.locations')),
    path('criterium/', include('criterium.urls', namespace = 'criterium')),
    path('archivio/', include('wordpress.urls', namespace = 'wordpress')),
    path('streamfield/', include('streamfield.urls')),
    path('favicon.ico',
        RedirectView.as_view(url=settings.STATIC_ROOT + 'images/favicon.ico')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import (FrontLoginView, FrontLogoutView, FrontPasswordResetView,
    TemplateResetView, FrontPasswordResetConfirmView, TemplateResetDoneView,
    TemplateAccountView, FrontPasswordChangeView, FrontPasswordChangeDoneView,
    ProfileChangeUpdateView)

#namespace is '/accounts/'
urlpatterns = [
    path('profile/', TemplateAccountView.as_view(),
        name='profile'),
    path('profile/<int:pk>/change', ProfileChangeUpdateView.as_view(),
        name='profile_change'),
    path('login/', FrontLoginView.as_view(),
        name='front_login'),
    path('logout/', FrontLogoutView.as_view(),
        name='front_logout'),
    path('password_reset/', FrontPasswordResetView.as_view(),
        name='front_password_reset'),
    path('password_reset/done/', TemplateResetView.as_view(),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', FrontPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', TemplateResetDoneView.as_view(),
        name='password_reset_complete'),
    path('password_change/', FrontPasswordChangeView.as_view(),
        name='password_change'),
    path('password_change_done/', FrontPasswordChangeDoneView.as_view(),
        name='password_change_done'),
    ]

pagine/models.py
import os
import re
from PIL import Image
from datetime import datetime
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.timezone import now
from django.utils.html import format_html
from django.utils.text import slugify
from filebrowser.fields import FileBrowseField
from taggit.managers import TaggableManager
from streamfield.fields import StreamField
from streamblocks.models import (IndexedParagraph, CaptionedImage, Gallery,
    LandscapeGallery, DownloadableFile, LinkableList, BoxedText, EventUpgrade)
from .choices import *
from users.models import User, Member

def date_directory_path(instance, filename):
    if instance.date:
        now = instance.date
    else:
        now = datetime.now()
    year = now.strftime("%Y")
    month = now.strftime("%m")
    day = now.strftime("%d")
    return 'uploads/{0}/{1}/{2}/{3}'.format(year, month, day, filename)

def generate_unique_slug(klass, field):
    """
    return unique slug if origin slug exists.
    eg: `foo-bar` => `foo-bar-1`

    :param `klass` is Class model.
    :param `field` is specific field for title.
    Thanks to djangosnippets.org!
    """
    origin_slug = slugify(field)
    unique_slug = origin_slug
    numb = 1
    while klass.objects.filter(slug=unique_slug).exists():
        unique_slug = '%s-%d' % (origin_slug, numb)
        numb += 1
    return unique_slug

class Location(models.Model):
    fb_image = FileBrowseField("Immagine", max_length=200,
        directory="locations/", extensions=[".jpg", ".png", ".jpeg", ".gif",
        ".tif", ".tiff"], null=True, blank=True)
    title = models.CharField('Titolo',
        help_text='Il nome del luogo',
        max_length = 50)
    slug = models.SlugField(max_length=50, unique=True)
    address = models.CharField('Indirizzo', max_length = 200,
        help_text = 'Via/Piazza, civico, CAP, Città',)
    gmap_link = models.URLField('Link di Google Map',
        blank= True, null=True,
        help_text="Dal menu di Google Maps seleziona 'Condividi/link', \
                   copia il link e incollalo qui",
    )
    gmap_embed = models.TextField('Incorpora Google Map',
        blank= True, null=True, max_length=500,
        help_text="Dal menu di Google Maps seleziona 'Condividi/incorpora', \
                   copia il link e incollalo qui",
    )
    body = models.TextField('Descrizione', blank= True, null=True,)
    website = models.URLField('Sito internet',
        blank= True, null=True, )
    email = models.EmailField(blank = True, null = True,
        verbose_name = 'Email',)
    phone = models.CharField(max_length = 50,
        blank = True, null = True, verbose_name = 'Telefono/i',)

    def save(self, *args, **kwargs):
        if not self.gmap_embed.startswith('http'):
            # thanks to geeksforgeeks.com! findall returns a list
            list = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\), ]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', self.gmap_embed)
            if list:
                self.gmap_embed = list[0]
        if not self.slug:  # create
            self.slug = generate_unique_slug(Location, self.title)
        super(Location, self).save(*args, **kwargs)

    def get_gmap_link(self):
        if self.gmap_link:
            link = format_html('<a href="{}" class="btn" target="_blank">Mappa</a>',
                self.gmap_link)
        else:
            link = '-'
        return link
    get_gmap_link.short_description = 'Link di Google Maps'

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Luogo'
        verbose_name_plural = 'Luoghi'
        ordering = ('id', )

def update_indexed_paragraphs(stream_list, type, id):
    for block in stream_list:
        if block['model_name'] == 'IndexedParagraph':
            par = IndexedParagraph.objects.get(id = block['id'])
            par.parent_type = type
            par.parent_id = id
            par.save()

class Event(models.Model):
    fb_image = FileBrowseField("Immagine", max_length=200, directory="events/",
        extensions=[".jpg", ".png", ".jpeg", ".gif", ".tif", ".tiff"],
        null=True, blank=True)
    carousel = StreamField(model_list=[ LandscapeGallery, ],
        null=True, blank=True, verbose_name="Galleria",
        help_text="Una sola galleria, per favore, larghezza minima immagini 2048px")
    title = models.CharField('Titolo',
        help_text="Il titolo dell'evento",
        max_length = 50)
    slug = models.SlugField(max_length=50, editable=False, null=True)
    date = models.DateTimeField('Quando', default = now)
    last_updated = models.DateTimeField(editable=False, null=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL,
        null = True, verbose_name = 'Dove', )
    intro = models.CharField('Introduzione',
        default = 'Un altro appuntamento con RP!', max_length = 100)
    stream = StreamField(model_list=[ IndexedParagraph, CaptionedImage,
        Gallery, DownloadableFile, LinkableList, BoxedText, ],
        verbose_name="Lancio")
    upgrade_stream = StreamField(model_list=[ EventUpgrade, IndexedParagraph,
        DownloadableFile, ],
        verbose_name="Aggiornamenti")
    chron_stream = StreamField(model_list=[ IndexedParagraph, CaptionedImage,
        Gallery, DownloadableFile, LinkableList, BoxedText],
        verbose_name="Cronaca")
    restr_stream = StreamField(model_list=[ IndexedParagraph, CaptionedImage,
        Gallery, DownloadableFile, LinkableList, BoxedText],
        verbose_name="Area riservata",
        help_text="Inserisci qui materiale riservato ai soci",)
    manager = models.ForeignKey(User, on_delete=models.SET_NULL,
        blank= True, null=True, verbose_name = 'Responsabile')
    tags = TaggableManager(verbose_name="Categorie",
        help_text="Lista di categorie separate da virgole",
        through=None, blank=True)
    notice = models.CharField(max_length = 4, choices = NOTICE,
        blank = True, null = True, verbose_name = 'Notifica via email',
        help_text = """Non invia in automatico, per farlo seleziona l'Evento
            dalla Lista degli Eventi, imposta l'azione 'Invia notifica' e fai
            clic su 'Vai'.
            """)

    def get_badge_color(self):
        if self.date.date() > datetime.today().date():
            return 'success'
        elif self.date.date() < datetime.today().date():
            return 'secondary'
        else:
            return 'warning'

    def get_image(self):
        if self.fb_image:
            return self.fb_image
        elif self.location.fb_image:
            return self.location.fb_image
        return

    def get_tags(self):
        return list(self.tags.names())

    def get_upgrades(self):
        return EventUpgrade.objects.filter(event_id=self.id)

    def get_chronicle(self):
        if self.date.date() < datetime.today().date():
            return True
        return False

    def get_uploads(self):
        return UserUpload.objects.filter(event_id=self.id)

    def get_path(self):
        return '/calendario/' + self.date.strftime("%Y/%m/%d") + '/' + self.slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_unique_slug(Event, self.title)
        if not self.notice:
            self.notice = 'SPAM'
        self.last_updated = now()
        super(Event, self).save(*args, **kwargs)
        #update parent_type end parent_id in IndexedParagraph streamblocks
        type = ContentType.objects.get(app_label='pagine', model='event').id
        id = self.id
        stream_list = self.stream.from_json()
        update_indexed_paragraphs(stream_list, type, id)
        stream_list = self.upgrade_stream.from_json()
        update_indexed_paragraphs(stream_list, type, id)
        stream_list = self.chron_stream.from_json()
        update_indexed_paragraphs(stream_list, type, id)
        stream_list = self.restr_stream.from_json()
        update_indexed_paragraphs(stream_list, type, id)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Evento'
        verbose_name_plural = 'Eventi'
        ordering = ('-date', )

class EventUpgrade(models.Model):
    event = models.ForeignKey(Event, on_delete = models.CASCADE,
        null = True, related_name='event_upgrades')
    title = models.CharField('Titolo',
        help_text="Il titolo dell'aggiornamento",
        max_length = 50)
    date = models.DateTimeField('Data', default = now)
    body = models.TextField('Aggiornamento',
        help_text = "Accetta tag HTML.", )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Aggiornamento'
        verbose_name_plural = 'Aggiornamenti'
        ordering = ('-date', )

class Blog(models.Model):
    fb_image = FileBrowseField("Immagine", max_length=200, directory="blogs/",
        extensions=[".jpg", ".png", ".jpeg", ".gif", ".tif", ".tiff"],
        null=True, blank=True)
    carousel = StreamField(model_list=[ LandscapeGallery, ],
        null=True, blank=True, verbose_name="Galleria",
        help_text="Una sola galleria, per favore, larghezza minima immagini 2048px")
    title = models.CharField('Titolo',
        help_text="Il titolo dell'articolo",
        max_length = 50)
    slug = models.SlugField(max_length=50, editable=False, null=True)
    date = models.DateTimeField('Data', default = now)
    last_updated = models.DateTimeField(editable=False, null=True)
    intro = models.CharField('Introduzione',
        default = 'Un altro articolo di approfondimento da RP!', max_length = 100)
    stream = StreamField( model_list=[ IndexedParagraph, CaptionedImage,
            Gallery, DownloadableFile, LinkableList, BoxedText],
            verbose_name="Testo" )
    author = models.ForeignKey(User, on_delete=models.SET_NULL,
        blank= True, null=True, verbose_name = 'Autore')
    tags = TaggableManager(verbose_name="Categorie",

pagine/forms.py
from django import forms
from django.forms import ModelForm
from .models import UserUpload, Event, Blog
from users.models import User

class UserUploadForm(ModelForm):
    body = forms.CharField(label = 'Testo',
        widget=forms.Textarea(attrs={'placeholder': "Scrivi qui il messaggio"}))
    class Meta:
        model = UserUpload
        fields = ('image', 'body',)

class EventForm(ModelForm):
    manager = forms.ModelChoiceField(label="Responsabile", required = False,
        queryset = User.objects.with_perm('pagine.add_event').order_by('username'), )

    class Meta:
        model = Event
        fields = '__all__'

class BlogForm(ModelForm):
    author = forms.ModelChoiceField(label="Autore", required = False,
        queryset = User.objects.filter(is_active = True, ).order_by('username'), )

    class Meta:
        model = Blog
        fields = '__all__'

pagine/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import (ListView, DetailView, CreateView,
    TemplateView)
from django.views.generic.dates import (ArchiveIndexView, YearArchiveView,
    MonthArchiveView, DayArchiveView, )
from taggit.models import Tag

from .forms import UserUploadForm
from .models import (Location, Event, UserUpload, Blog)

class HomeTemplateView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_events'] = Event.objects.all()[:6]
        context['posts'] = Blog.objects.all()[:6]
        return context

class ListLocation(ListView):
    model = Location
    context_object_name = 'all_locations'
    paginate_by = 12

class DetailLocation(DetailView):
    model = Location
    context_object_name = 'location'
    slug_field = 'slug'

class TagMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        if 'categoria' in self.request.GET:
            context['tag_filter'] = self.request.GET['categoria']
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        if 'categoria' in self.request.GET:
            qs = qs.filter(tags__name=self.request.GET['categoria'])
        return qs

class EventArchiveIndexView(TagMixin, ArchiveIndexView):
    model = Event
    date_field = 'date'
    allow_future = True
    context_object_name = 'all_events'
    paginate_by = 12
    allow_empty = True

class EventYearArchiveView(TagMixin, YearArchiveView):
    model = Event
    make_object_list = True
    date_field = 'date'
    allow_future = True
    context_object_name = 'all_events'
    paginate_by = 12
    year_format = '%Y'
    allow_empty = True

class EventMonthArchiveView(TagMixin, MonthArchiveView):
    model = Event
    date_field = 'date'
    allow_future = True
    context_object_name = 'all_events'
    year_format = '%Y'
    month_format = '%m'
    allow_empty = True

class EventDayArchiveView(TagMixin, DayArchiveView):
    model = Event
    date_field = 'date'
    allow_future = True
    context_object_name = 'all_events'
    year_format = '%Y'
    month_format = '%m'
    day_format = '%d'
    allow_empty = True

class DetailEvent(DetailView):
    model = Event
    context_object_name = 'event'
    slug_field = 'slug'

class ListBlog(TagMixin, ListView):
    model = Blog
    ordering = ('-date', )
    context_object_name = 'posts'
    paginate_by = 12

class DetailBlog(DetailView):
    model = Blog
    context_object_name = 'post'
    slug_field = 'slug'

class UserUploadCreateView(LoginRequiredMixin, CreateView):
    model = UserUpload
    form_class = UserUploadForm

    def get_success_url(self):
        if 'event_id' in self.request.GET:
            evt = Event.objects.get(id=self.request.GET['event_id'])
            return evt.get_path() + '/#upload-anchor'
        elif 'post_id' in self.request.GET:
            pst = Blog.objects.get(id=self.request.GET['post_id'])
            return pst.get_path() + '/#upload-anchor'

    def form_valid(self, form):
        form.instance.user = self.request.user
        if 'event_id' in self.request.GET:
            form.instance.event = Event.objects.get(id=self.request.GET['event_id'])
        elif 'post_id' in self.request.GET:
            form.instance.post = Blog.objects.get(id=self.request.GET['post_id'])
        return super().form_valid(form)

pagine/templates/pagine/blog_detail.html
{% extends 'base.html' %}

{% block title %}RP | {{ post.title }}{% endblock title %}

{% block content %}
      {% if post.carousel.render %}
        <div class="row">
          {{ post.carousel.render }}
        </div>
      {% elif post.fb_image %}
        <div class="row">
          <img src="{{ post.fb_image.url }}" width="100%" alt="{{ post.intro }}" />
        </div>
      {% endif %}
      <div class="row row-striped">
        <div class="col-md-2"></div>
        <div class="col-md-10">
          <h3 class="text-uppercase"><strong>{{ post.title }}</strong></h3>
          <ul class="list-inline">
            {% if post.author %}
            <li class="list-inline-item">
              <i class="fa fa-user" aria-hidden="true"></i>
              {% if user.is_authenticated %}
              <a href="/contacts/?recipient={{ post.author_id }}&subject={{ post.title }}">{{ post.author }}</a>
              {% else %}
              {{ post.author }}
              {% endif %}
            </li>
            {% endif %}
            <li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i> {{ post.date|date:"d M Y" }}</li>
            {% if post.get_tags %}
              <li class="list-inline-item">
                <i class="fa fa-folder-open" aria-hidden="true"></i>
                {% for tag in post.get_tags %}
                  <a href="/articoli/?categoria={{ tag }}">{{ tag|upper }}</a>
                {% endfor %}
              </li>
            {% endif %}
            {% if perms.pagine.change_blog %}
            <li class="list-inline-item">
              <i class="fa fa-pencil" aria-hidden="true"></i>
              <a href="/admin/pagine/blog/{{ post.id }}/change/">Modifica</a>
            </li>
            {% endif %}
          </ul>
          <p>{{ post.intro }}</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          {{ post.stream.render }}
          <hr class="mb-4">
          {% if user.is_authenticated %}
            <div class="row">
              <h4 id="upload-anchor"><strong>Contributi</strong></h4>
            </div>
            <div>
              <a href="/articoli/contributi/?post_id={{ post.id }}">
              Aggiungi un contributo</a>
            </div>
            {% if post.get_uploads %}
            <hr class="mb-4">
            <div class="card-deck">
              {% for upload in post.get_uploads %}
                {% include 'pagine/uploads.html' %}
              {% endfor %}
            </div>
            {% endif %}
          {% else %}
            <div>
              Esegui il <a href="/admin/login/?next={{ request.get_full_path }}">&nbsp;login&nbsp;</a> se vuoi aggiungere un contributo
            </div>
            <hr class="mb-4">
          {% endif %}
        </div>
      </div>
{% endblock content %}

pagine/templates/pagine/blog_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}RP | Articoli{% endblock title %}
{% block content %}
{% if tags %}
  <p>Filtra per categoria:
  {% for tag_item in tags %}
    {% if tag_item.name == tag_filter %}
    {% else %}
      <a href="{{ request.path }}?categoria={{ tag_item.name }}">{{ tag_item.name|upper }}</a>
    {% endif %}
  {% endfor %}
  </p>
{% endif %}
  <h4><strong>
    Articoli di approfondimento
    {% if tag_filter %} nella categoria: {{ tag_filter|upper }}{% endif %}
  </strong></h4>
{% if posts %}
<div class="card-deck">
{% for post in posts %}
  <div class="card" style="margin-bottom: 20px; min-width: 18rem;">
    <div class="card-header">
      <h4 class="card-title">
      <a href="/articoli/{{ post.slug }}">
        {{ post.title }}</a></h4>
    </div>
    <img class="card-img-top" src="{{ post.fb_image.url }}" alt="{{ post.intro }}">
    <div class="card-body">
      <em class="card-text">{{ post.intro }}</em>
      <ul class="list-inline">
        <li class="list-inline-item">
          {% if post.author %}
          <i class="fa fa-user" aria-hidden="true"></i>
          {{ post.author.get_full_name_reverse }}
          {% endif %}
        </li>
        <li class="list-inline-item">
          <i class="fa fa-calendar-o" aria-hidden="true"></i>
          {{ post.date|date:"d M Y" }}
        </li>
        {% if post.get_tags %}
          <li class="list-inline-item">
            <i class="fa fa-folder-open" aria-hidden="true"></i>
            {% for tag in post.get_tags %}
              {{ tag|upper }}
            {% endfor %}
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
{% endfor %}
</div>
{% else %}
<p>Non sono disponibili articoli</p>
{% endif %}
{% if is_paginated %}
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PRECEDENTI </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> PROSSIMI &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endif %}
{% endblock content %}

pagine/templates/pagine/event_archive.html
{% extends 'pagine/event_archive_general.html' %}

{% block title %}RP | Calendario{% endblock title %}
{% block event_archive %}
<h4><strong>
  Appuntamenti e cronache
  {% if tag_filter %} nella categoria: {{ tag_filter|upper }}{% endif %}
</strong></h4>
<hr class="mb-4">
{% if all_events %}
    {% for event in all_events %}
      <div class="row row-striped">
        <div class="col-md-2 text-right">
          <h1 class="display-4"><span class="badge badge-{{ event.get_badge_color }}">{{ event.date|date:"j" }}</span></h1>
          <a href="/calendario/{{ event.date|date:"Y/m" }}/"><h4>{{ event.date|date:"M-Y" }}</h4></a>
        </div>
        <div class="col-md-10">
          <h3 class="text-uppercase"><strong><a href="/calendario/{{ event.date|date:"Y/m/d" }}/{{ event.slug }}">{{ event.title }}</a></strong></h3>
          <p>{{ event.intro }}</p>
          <ul class="list-inline">
            {% include 'pagine/event_list_inline.html'%}
            {% include 'pagine/event_list_inline_2.html'%}
          </ul>
        </div>
      </div>
    {% endfor %}
{% else %}
    <div class="col-md-12">
        <p>Non ci sono eventi in calendario.</p>
    </div>
{% endif %}
<hr class="mb-4">
{% if is_paginated %}
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PRECEDENTI </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> PROSSIMI &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endif %}
{% endblock event_archive %}

pagine/templates/pagine/event_archive_day.html
{% extends 'pagine/event_archive_general.html' %}

{% block title %}RP | Calendario {{ day }}{% endblock title %}
{% block event_archive %}
<h4><strong>
  Appuntamenti e cronache {{ day }}
  {% if tag_filter %} nella categoria: {{ tag_filter|upper }}{% endif %}
</strong></h4>
<hr class="mb-4">
{% if all_events %}
    {% for event in all_events %}
      <div class="row row-striped">
        <div class="col-md-2 text-right">
          <h1 class="display-4"><span class="badge badge-{{ event.get_badge_color }}">{{ event.date|date:"j" }}</span></h1>
          <a href="/calendario/{{ event.date|date:"Y/m" }}/"><h4>{{ event.date|date:"M-Y" }}</h4></a>
        </div>
        <div class="col-md-10">
          <h3 class="text-uppercase"><strong><a href="/calendario/{{ event.date|date:"Y/m/d" }}/{{ event.slug }}">{{ event.title }}</a></strong></h3>
          <p>{{ event.intro }}</p>
          <ul class="list-inline">
            {% include 'pagine/event_list_inline.html'%}
            {% include 'pagine/event_list_inline_2.html'%}
          </ul>
        </div>
      </div>
    {% endfor %}
{% else %}
    <div class="col-md-12">
        <p>Non ci sono eventi in calendario.</p>
    </div>
{% endif %}
<hr class="mb-4">
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if previous_day %}
    <li><a href="/calendario/{{ previous_day|date:"Y/m/d" }}" class="page-link">&laquo; PRECEDENTE </a></li>
    {% endif %}
    {% if next_day %}
    <li><a href="/calendario/{{ next_day|date:"Y/m/d" }}" class="page-link"> SUCCESSIVO &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endblock event_archive %}

pagine/templates/pagine/event_list_inline.html
<li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i>
  {{ event.date|date:"l" }}</li>
<li class="list-inline-item"><i class="fa fa-clock-o" aria-hidden="true"></i>
  {{ event.date|date:"H:i" }}</li>
<li class="list-inline-item"><i class="fa fa-location-arrow" aria-hidden="true"></i>
  <a href="/luoghi/{{ event.location.slug }}">{{ event.location.title }}</a></li>

{% if event.manager %}
  <li class="list-inline-item">
    <i class="fa fa-user" aria-hidden="true"></i>
    {% if user.is_authenticated %}
      <a href="/contacts/?recipient={{ event.manager_id }}">
        {{ event.manager.get_full_name_reverse }}</a>
    {% else %}
      {{ event.manager.get_full_name_reverse }}
    {% endif %}
  </li>
{% endif %}

<li class="list-inline-item">
  <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
  Ultima modifica: {{ event.last_updated|date:"d M Y" }}
</li>

{% if perms.pagine.change_event %}
<li class="list-inline-item">
  <i class="fa fa-pencil" aria-hidden="true"></i>
  <a href="/admin/pagine/event/{{ event.id }}/change/">Modifica</a>
</li>
{% endif %}